### ISSUE TITLE
Trimethyl install bug

### ISSUE THREAD

**Issue by ikalangita** [trimethyl/trimethyl#46]
Hello,

Si i followed this post : [https://developers.caffeina.com/crosplatform-app-development-907a9788c668](url)

when install a module : 
- trimethyl install
- select module with keyboard space
- hit enter

I got error : 
`<Bootstrap> is not a valid Trimethyl library./usr/local/lib/node_modules/trimethyl/cli.js:412
	if (trimethyl_map[name].internal) {
	                        ^

TypeError: Cannot read property 'internal' of undefined
    at Command.<anonymous> (/usr/local/lib/node_modules/trimethyl/cli.js:412:26)
    at Command.listener (/usr/local/lib/node_modules/trimethyl/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/local/lib/node_modules/trimethyl/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/trimethyl/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/trimethyl/cli.js:468:9)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
`

**Comment by kopiro** [comment]
Don't add `boostrap` as a module.
